### ISSUE TITLE
/proc mounted under wrong group

### ISSUE THREAD

**Issue by atomass** [google/nsjail#126]
Hi,
using this command line:
```
./nsjail -Ml --port 9000 --rw --proc_rw --chroot `pwd`/chroot/ --user 0:`id -u`:1 --group 0:`id -g`:1 -- /bin/sh -i
```
will result in having `/proc` mounted under both `uid` and `gid` `65534`:
```
# ls -la
total 84
drwxr-xr-x   22 root     root          4096 Oct 22 12:31 .
drwxr-xr-x   22 root     root          4096 Oct 22 12:31 ..
drwxr-xr-x    2 root     root          4096 Oct 22 10:26 bin
drwxr-xr-x    2 root     root          4096 Oct 22 09:54 dev
drwxr-xr-x    3 root     root          4096 Sep 10 09:16 etc
drwxr-xr-x    4 root     root          4096 Sep 10 09:16 lib
dr-xr-xr-x  419 65534    65534            0 Oct 22 13:19 proc
drwxr-xr-x    3 root     root          4096 Oct 22 13:05 ram
drwxr-xr-x    2 root     root          4096 Sep 10 09:16 sbin
drwxr-xr-x    2 root     root          4096 Sep 10 09:16 sys
drwxrwxr-x    2 root     root          4096 Oct 22 13:12 tmp
drwxr-xr-x    4 root     root          4096 Oct 14 17:06 usr
drwxr-xr-x    6 root     root          4096 Oct 22 08:33 var
```
Everything under the `chroot/` folder is owned by the user that is issuing the command.
Am I missing something ?

**Comment by happyCoder92** [comment]
Hi,

/proc is always owned by the global root:root (uid=0, gid=0 in initial user namespace).
It shows as overflow uid/gid (65534), because global root is not mapped (and most probably should not be mapped) in your userns.

**Comment by atomass** [comment]
So, I don't get the meaning of having the option ` --proc_rw ` if being root in the jail is not still enough to write on jail's `proc` fs.

**Comment by disconnect3d** [comment]
> is not still enough to write on jail's proc fs.

What makes you think that?

I haven't checked that but my guess is that `--proc_rw` makes a `rw` mount of `/proc`.

Let's look at how it looks on a default ubuntu installation:
```
$ mount | grep proc
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)

$ ls -la / | grep proc
dr-xr-xr-x 211 root root          0 Aug 26 11:50 proc
```

Having a different owner/group of a `/proc` file is totally fine as long as you can access it, and we have `--x` as others, so we can indeed enter the directory.

As a result, since we have a `rw` mount, *there will be some files we will be able to write to* (and that's the whole purpose of a RW /proc mount).

Note that this might allow for some privilege escalations. For example Docker mounts proc as RO by default AND ALSO denies some accesses via apparmor: https://github.com/moby/moby/blob/master/profiles/apparmor/template.go#L27-L33

...and a read-only `/proc` mount can also leak some information. One example is leaking info about played audio via `/proc/asound` which was an issue back then in Docker: https://github.com/moby/moby/issues/38285

Since I already wrote some stuff, I might also drop some links related to Docker and containers in general:
- [Brandon Edwards & Nick Freeman: "Compendium of Container Escapes" from BH USA 2019](https://i.blackhat.com/USA-19/Thursday/us-19-Edwards-Compendium-Of-Container-Escapes-up.pdf)
- My talk from AlligatorConEU: [Fancy "privileged" Docker container escapes](https://docs.google.com/presentation/d/1tCqmGSOJJzi6ZK7TNhbzVFsTekvjvQR8GGPoaYBrM1o)
- My post on Trail of Bits blog on ["Understanding Docker container escapes"](https://blog.trailofbits.com/2019/07/19/understanding-docker-container-escapes/) - this is a write-up of one of "privileged" container escape

**Comment by atomass** [comment]
Hi @disconnect3d,
thank for the information but they didn't apply to my case.
As I previously wrote in my first comment, the `/proc` folder in the jail has a different owner:
```
dr-xr-xr-x  419 65534    65534            0 Oct 22 13:19 proc
```
thus resulting non-writable by the `root` jail user.
```
/ # /bin/busybox whoami
root
/ # /bin/busybox id
uid=0(root) gid=0(root) groups=65534,65534,65534,65534,65534,65534,65534,65534,65534,0(root)
/ # echo 0 > /proc/sys/net/ipv4/ip_forward
/bin/sh: can't create /proc/sys/net/ipv4/ip_forward: Permission denied
```
Any ideas?

**Comment by happyCoder92** [comment]
Hi,

In that case you're missing CAP_NET_ADMIN.
You can retain the capability by using --cap CAP_NET_ADMIN or --keep_caps (you will keep all the capabilites then).

**Comment by atomass** [comment]
Hi @happyCoder92,
thank you to have point me out to the right direction and sorry to have bothered you.
