### ISSUE TITLE
Unable to find included bashscript file 

### ISSUE THREAD

**Issue by edwardt** [google/nsjail#165]
Have 2 bashscripts

bashA.sh:
#!/usr/bin/env bash
wa() {
  echo "1223"
}

bashB.sh
#!/usr/bin/env bash
. bashA
wa()

Both scripts in the samer directory called it MYHOME/script/bin

mount {
	prefix_src_env: "MHOME"
	prefix_dst_env: "MYHOME"
	src: "/script/bin"
	dst: "/script/bin"
	is_bind: true
	rw: false
}

But I am still getting complaints about bashA "file or directory not found" with nsjail on
With nsjail OFF, it is fine.
Anyone knows what is causing this?
I tried using source bashA instead of .  but with no improvements

**Comment by disconnect3d** [comment]
Can you provide us a minimal working example that can be used to reproduce your issue? Otherwise, it is hard to predict all the configuration choices made that may cause the result you see.

Can it be that you launch the `bashB.sh` script directly, with its full path and then the `bashA.sh` script is not in `$PATH`? It seems that maybe you wanted to do `. ./bashA.sh`, or, you may need to add the `/script/bin` directory to `$PATH` inside the jail.

**Comment by edwardt** [comment]
@disconnect3d 
I will get a minimal example and posted here.
About your comment of adding /script/bin directory to $PATH inside the jail, are you taking about
concat the script/bin to the current $PATH inside nsjai.cfg?
envar: "HOME=/"
envar: "PATH=$PATH:$HOME/script/bin"
inside nsjail.cfg?

**Comment by edwardt** [comment]
Update.
The issue was that relative paths, . or .. , are not honored in bashB.sh but was mapped to what cwd set in nsjail. config

**Comment by robertswiecki** [comment]
Closing as it seems the author of this bug report has it fixed.
