### ISSUE TITLE
Better fs isolation

### ISSUE THREAD

**Issue by 12D687** [google/nsjail#213]
Is it possible to replace the chroot with some sophisticated security feature (e.g LVM or btrfs subvolumes) for better filesystem isolation. Because in nowadays the chroot is way too easy to bypass so it doesn't provide proper fs isolation.

**Comment by Karmadark2light** [comment]
Please explain “isolation”

**Comment by disconnect3d** [comment]
**Summary: this issue can probably be closed as Nsjail does provide a better way than chroot to isolate fs.**

> Is it possible to replace the chroot with some sophisticated security feature (e.g LVM or btrfs subvolumes) for better filesystem isolation.

You do not have to use `chroot` at all with Nsjail since it uses mount namespaces by default and by default the `/` path in the jail is mounted/created as a tmpfs. I will provide some examples below.

Also, if you want to have a path from the host mounted as `/` into the jail, you can do so with bind mounts as well. Such mount just needs to be the first mount (other mounts would make little sense before mounting "/"). This can also allow you to use a LVM or BTRFS  subvolumes, assuming you create such mounts first on the host. Though, I don't understand if or why any of those would provide "some sophisticated security feature".

> Because in nowadays the chroot is way too easy to bypass so it doesn't provide proper fs isolation.

Any specific case you have in mind that you could showcase? The Nsjail help states:
```
  --chroot|-c VALUE
 	Directory containing / of the jail (default: none)
  --no_pivotroot
 	When creating a mount namespace, use mount(MS_MOVE) and chroot rather than pivot_root. Usefull when pivot_root is disallowed (e.g. initramfs). Note: escapable is some configuration
```

I haven't analyzed it, but can you escape from just a `--chroot <path>` if `--no_pivotroot` is not used?

--- 

### Examples of running Nsjail without --chroot

```
root@pwndbg-dev:~/nsjail# strace -fff -e chroot ./nsjail -Mo --bindmount_ro /lib/x86_64-linux-gnu/libselinux.so.1 --bindmount_ro /lib/x86_64-linux-gnu/libc.so.6 --bindmount_ro /lib/x86_64-linux-gnu/libpcre2-8.so.0 --bindmount_ro /lib64/ld-linux-x86-64.so.2 --bindmount_ro /bin/ls --bindmount_ro /bin/cat -- /bin/cat /proc/mounts
[I][2023-02-20T20:34:16+0000] Mode: STANDALONE_ONCE
[I][2023-02-20T20:34:16+0000] Jail parameters: hostname:'NSJAIL', chroot:'', process:'/bin/cat', bind:[::]:0, max_conns:0, max_conns_per_ip:0, time_limit:0, personality:0, daemonize:false, clone_newnet:true, clone_newuser:true, clone_newns:true, clone_newpid:true, clone_newipc:true, clone_newuts:true, clone_newcgroup:true, clone_newtime:false, keep_caps:false, disable_no_new_privs:false, max_cpus:0
[I][2023-02-20T20:34:16+0000] Mount: '/' flags:MS_RDONLY type:'tmpfs' options:'' dir:true
[I][2023-02-20T20:34:16+0000] Mount: '/lib/x86_64-linux-gnu/libselinux.so.1' -> '/lib/x86_64-linux-gnu/libselinux.so.1' flags:MS_RDONLY|MS_BIND|MS_REC|MS_PRIVATE type:'' options:'' dir:false
[I][2023-02-20T20:34:16+0000] Mount: '/lib/x86_64-linux-gnu/libc.so.6' -> '/lib/x86_64-linux-gnu/libc.so.6' flags:MS_RDONLY|MS_BIND|MS_REC|MS_PRIVATE type:'' options:'' dir:false
[I][2023-02-20T20:34:16+0000] Mount: '/lib/x86_64-linux-gnu/libpcre2-8.so.0' -> '/lib/x86_64-linux-gnu/libpcre2-8.so.0' flags:MS_RDONLY|MS_BIND|MS_REC|MS_PRIVATE type:'' options:'' dir:false
[I][2023-02-20T20:34:16+0000] Mount: '/lib64/ld-linux-x86-64.so.2' -> '/lib64/ld-linux-x86-64.so.2' flags:MS_RDONLY|MS_BIND|MS_REC|MS_PRIVATE type:'' options:'' dir:false
[I][2023-02-20T20:34:16+0000] Mount: '/bin/ls' -> '/bin/ls' flags:MS_RDONLY|MS_BIND|MS_REC|MS_PRIVATE type:'' options:'' dir:false
[I][2023-02-20T20:34:16+0000] Mount: '/bin/cat' -> '/bin/cat' flags:MS_RDONLY|MS_BIND|MS_REC|MS_PRIVATE type:'' options:'' dir:false
[I][2023-02-20T20:34:16+0000] Mount: '/proc' flags:MS_RDONLY type:'proc' options:'' dir:true
[I][2023-02-20T20:34:16+0000] Uid map: inside_uid:0 outside_uid:0 count:1 newuidmap:false
[W][2023-02-20T20:34:16+0000][48709] logParams():266 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[I][2023-02-20T20:34:16+0000] Gid map: inside_gid:0 outside_gid:0 count:1 newgidmap:false
[W][2023-02-20T20:34:16+0000][48709] logParams():276 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
strace: Process 48710 attached
[I][2023-02-20T20:34:17+0000] Executing '/bin/cat' for '[STANDALONE MODE]'
none / tmpfs ro,relatime,inode64 0 0
/dev/vda1 /lib/x86_64-linux-gnu/libselinux.so.1 ext4 ro,relatime,discard,errors=remount-ro 0 0
/dev/vda1 /lib/x86_64-linux-gnu/libc.so.6 ext4 ro,relatime,discard,errors=remount-ro 0 0
/dev/vda1 /lib/x86_64-linux-gnu/libpcre2-8.so.0 ext4 ro,relatime,discard,errors=remount-ro 0 0
/dev/vda1 /lib64/ld-linux-x86-64.so.2 ext4 ro,relatime,discard,errors=remount-ro 0 0
/dev/vda1 /bin/ls ext4 ro,relatime,discard,errors=remount-ro 0 0
/dev/vda1 /bin/cat ext4 ro,relatime,discard,errors=remount-ro 0 0
none /proc proc ro,relatime 0 0
```

As you can see, no `chroot` was invoked and the jail contains only `/` as tmpfs, things we bind mounted to it and proc filesystem mounted as read-only. The proc filesystem can additionally be removed by setting `--disable_proc`.

### Your "typical" Nsjail run

Btw you should probably not run Nsjail from commandline and you should use a config file instead. You can see some example configs in https://github.com/google/nsjail/tree/master/configs or, e.g., in https://github.com/justcatthefish/justctf-2022/blob/main/challenges/pwn_dumpme/private/private/nsjail.cfg (that's how I hosted CTF tasks during some competitions).

**Comment by 12D687** [comment]
@Karmadark2light
It should be obvious when I say isolation. It means that you create separate filesystem which is separate from the main filesystem. 
@disconnect3d 
Sorry my mistake. I thought you use chroot as an mount isolation (as you said in Readme FS constrains). Since you can run the nsjail without chroot, this solves the problem.
